name: qr_4_all
description: Navigation app for traveling


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+5

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_storage: ^11.0.10
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1
  google_maps_flutter: ^2.1.0
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  carousel_slider: ^4.0.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.0.17
  flowder: ^0.2.0
  path_provider: ^2.0.8
  json_annotation: ^4.3.0
  location: ^4.3.0
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  shared_preferences: ^2.0.12
  after_layout: ^1.1.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^9.4.0
  webview_flutter: ^3.0.1
  fluttertoast: ^8.0.9
  android_intent_plus: ^3.1.5
  point_in_polygon: ^1.0.0
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/gals/
    - assets/en-gals.json
    - assets/ro-gals.json
    - assets/gals/icons/obj.png
    - assets/gals/icons/qr.png
    - assets/gals/icons/arrow.png
    - assets/gals/icons/www.png
    - assets/gals/icons/www2.png
    - assets/gals/icons/yt.png
    - assets/gals/icons/fb.png
    - assets/gals/icons/mech.png
    - assets/gals/icons/download.png
    - assets/gals/icons/map.png
    - assets/gals/icons/insta.png
    - assets/gals/icons/date.png
    - assets/gals/icons/direction.png